USE [master]
GO
/****** Object:  Database [AppDB]    Script Date: 16/09/2018 9:49:40 ******/
CREATE DATABASE [AppDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AppDB', FILENAME = N'C:\Users\guy.ekhauz\Documents\GuyDev_Ezbob_2018\MVC_CRUD_SAMPLE\CRUDAjax\CRUDAjax\App_Data\AppDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AppDB_log', FILENAME = N'C:\Users\guy.ekhauz\Documents\GuyDev_Ezbob_2018\MVC_CRUD_SAMPLE\CRUDAjax\CRUDAjax\App_Data\AppDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [AppDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AppDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AppDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AppDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AppDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AppDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [AppDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [AppDB] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [AppDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AppDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AppDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AppDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AppDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AppDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AppDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AppDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AppDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AppDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AppDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AppDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AppDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AppDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AppDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AppDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AppDB] SET  MULTI_USER 
GO
ALTER DATABASE [AppDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AppDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AppDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AppDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AppDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AppDB] SET QUERY_STORE = OFF
GO
USE [AppDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [AppDB]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 16/09/2018 9:49:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Age] [int] NULL,
	[State] [nvarchar](50) NULL,
	[Country] [nvarchar](50) NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[DeleteEmployee]    Script Date: 16/09/2018 9:49:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--Delete Employee
Create Procedure [dbo].[DeleteEmployee] 
( 
 @Id integer 
) 
as  
Begin 
 Delete Employee where EmployeeID=@Id; 
END 
GO
/****** Object:  StoredProcedure [dbo].[InsertUpdateEmployee]    Script Date: 16/09/2018 9:49:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--Insert and Update Employee
Create Procedure [dbo].[InsertUpdateEmployee] 
( 
@Id integer, 
@Name nvarchar(50), 
@Age integer, 
@State nvarchar(50), 
@Country nvarchar(50), 
@Action varchar(10) 
) 
As 
Begin 
if @Action='Insert' 
Begin 
 Insert into Employee(Name,Age,[State],Country) values(@Name,@Age,@State,@Country); 
End 
if @Action='Update' 
Begin 
 Update Employee set Name=@Name,Age=@Age,[State]=@State,Country=@Country where EmployeeID=@Id; 
End   
End
GO
/****** Object:  StoredProcedure [dbo].[SelectEmployee]    Script Date: 16/09/2018 9:49:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

 --Select Employees
Create Procedure [dbo].[SelectEmployee] 
as  
Begin 
Select * from Employee; 
End
GO
USE [master]
GO
ALTER DATABASE [AppDB] SET  READ_WRITE 
GO
